raise error if config/environment.erb miss necessary environment valuable (#868)
Making easy to find what is wrong when missing necessary environment valuable.

before:
```
Boot Error
Something went wrong while loading /your/repository/sample_hanami/config.ru

Hanami::Model::Error: LoadError: cannot load such file -- sequel/adapters/

/your/repository/sample_hanami/vendor/bundle/ruby/2.4.0/bundler/gems/model-22eb4b172cb5/lib/hanami/model/configuration.rb:144:in `rescue in load!'
/your/repository/sample_hanami/vendor/bundle/ruby/2.4.0/bundler/gems/model-22eb4b172cb5/lib/hanami/model/configuration.rb:134:in `load!'
...
```

after:
```
Boot Error
Something went wrong while loading /your/repository/sample_hanami/config.ru

KeyError: key not found: "DATABASE_URL"

/your/repository/sample_hanami/config/environment.rb:21:in `fetch'
/your/repository/sample_hanami/config/environment.rb:21:in `block (2 levels) in <top (required)>'
...
```