fix mistake of README#how-to-use-hanami-head (#867)
It causes error.

```bash
 $ bundle exec hanami new --hanami-head=true bookshelf
Error: Invalid param provided
```

The boolean option should be used without value.

refs: https://github.com/hanami/cli/#boolean-options